export interface EmployeeDto{
    id:string;
    name:string;
    surname:string;
    email:string;
    phoneNumber:number;
    age:number;
    departmentId:string;
    title:string;
    status:boolean;
    dateOfStart:string
    branchId:string;
    bloodGroup:string
    birthDay:string;
    educationalStatus:string
    lowerSize:string
    upperSize:string
    shoeSize:string
    dateOfFinish:string
    emergencyContactName:string
    emergencyContactNumber:string
    emergencyContactRelationship:string
}